create table if not exists public.brown_bag_slots (
  id bigint generated by default as identity primary key,
  slot_date date not null,
  title text not null,
  speaker text not null default 'TBD',
  notes text not null default '',
  display_order integer not null default 0,
  reserved_by text,
  reserved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.brown_bag_slots enable row level security;

drop policy if exists "Anyone can read slots" on public.brown_bag_slots;
create policy "Anyone can read slots"
  on public.brown_bag_slots
  for select
  using (true);

create or replace function public.reserve_brown_bag_slot(slot_id bigint, reserver_name text, talk_title text default null)
returns public.brown_bag_slots
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_slot public.brown_bag_slots;
  normalized_title text;
  normalized_name text;
begin
  normalized_title := nullif(trim(coalesce(talk_title, '')), '');
  normalized_name := trim(reserver_name);

  update public.brown_bag_slots
  set speaker = normalized_name,
      reserved_by = normalized_name,
      reserved_at = now(),
      updated_at = now(),
      title = coalesce(normalized_title, title)
  where id = slot_id
    and (
      reserved_by is null
      or lower(trim(coalesce(speaker, reserved_by, ''))) = lower(normalized_name)
      or lower(trim(reserved_by)) = lower(normalized_name)
    )
  returning * into updated_slot;

  if not found then
    raise exception 'Slot no disponible';
  end if;

  return updated_slot;
end;
$$;

create or replace function public.remove_brown_bag_slot(slot_id bigint, reserver_name text)
returns public.brown_bag_slots
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_slot public.brown_bag_slots;
begin
  update public.brown_bag_slots
  set speaker = 'TBD',
      reserved_by = null,
      reserved_at = null,
      updated_at = now()
  where id = slot_id
    and (
      reserved_by is not null
      or speaker is not null
    )
    and lower(trim(coalesce(speaker, reserved_by, ''))) = lower(trim(reserver_name))
  returning * into updated_slot;

  if not found then
    raise exception 'No puedes eliminar una reserva que no te pertenece';
  end if;

  return updated_slot;
end;
$$;

grant execute on function public.reserve_brown_bag_slot(bigint, text, text) to anon, authenticated;
grant execute on function public.remove_brown_bag_slot(bigint, text) to anon, authenticated;